#!/bin/sh

date=`date "+%Y-%m-%dT%H_%M_%S"`

rsync -azP \
  -e ssh \
  --delete \
  --delete-excluded \
  --link-dest=../current \
  $HOME/Dropbox $HOME/Projects $HOME/Documents $HOME/Pictures jarias@gray.carrillo::home/Backups/incomplete_back-$date \
  && ssh jarias@gray.carrillo \
  "mv Backups/incomplete_back-$date Backups/back-$date \
  && rm -f Backups/current \
  && ln -s back-$date Backups/current"
